### ISSUE TITLE
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by ikus060** [jenkinsci/gitlab-hook-plugin#21]
This problem seams to happen after an upgrade in Jenkins or Gitlab. I don't know which one since I didn't track the upgrade. My mistake.

See log in attachment.
[jenkins.txt](https://github.com/jenkinsci/gitlab-hook-plugin/files/110879/jenkins.txt)

GitLab Community Edition 8.4.0 1b1c0ba
Jenkins ver. 1.644
Gitlab Hook Plugin 1.4.1.1

Thanks for help

**Comment by javiplx** [comment]
From the line with the error, looks looks related with parametrization. Are you using in any of your rdiffweb* repos a parametrized branch name?
Not sure, but your error might happen if you use a git branch with a parameter but the project has no parameter defined. If that were the case, just appending ` or []` to line 98 of models/values/project.rb should work

**Comment by ikus060** [comment]
I've recently create a new project with parameters, but it's not related to 
Yep, I've recently create a new project with parameters. But it's not related to the repo `git.patrikdufresne.com:pdsl/rdiffweb.git`.

Also, none of the repo listed in the logs is parametrized.

**Comment by javiplx** [comment]
In any case, the fix I propose should work. Can you test it?
And if you could send me the config.xml for the rdiff* jobs, it might help to actually find the issue, even if the workaround works as expected.

**Comment by ikus060** [comment]
ha ha, just to make sure, I've double-check each project configuration. One of them was parameterized, but without a parameter :S.

Anyway, I've fix the configuration and it's working again.

**Comment by ikus060** [comment]
Thanks for you help and time !

**Comment by javiplx** [comment]
Could you explain me what change did you perform in the job? When trying to issue a warning for a case like yours, I've realized that a project without parameters should never reach the line with your exception, because the protection I wanted to introduce was already there.

**Comment by javiplx** [comment]
Forget my question. Looking again I see the issue now. At one place it checks if project is parametrized, that it does not mean that it has any parameter, which is the error reason. Now that I've seen it, I'll fix it and issue a warning to logfile

**Comment by inforedaster** [comment]
Hi what's the environment variable mean the branche name it is ${branche}
