### ISSUE TITLE
"No project references the given repo url" for a merge request

### ISSUE THREAD

**Issue by HadesArchitect** [jenkinsci/gitlab-hook-plugin#24]
Hello and thank you for the great plugin!

For the regular push-based builds everything works perfectly. For the merge-request based builds I receive all the time the same error:

~~~
Apr 04, 2016 1:51:53 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
INFO: matching projects:
    - test-project
Apr 04, 2016 1:51:53 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
WARNING: no project references the given repo url and commit branch
~~~

In a global configuration "Create new projects for merge requests" is enabled, of course.

In a project configuration: 
* Repository URL: git@git.qwerty.local:aleks/test-project.git
* Branch specifier: origin/master (though I've tried it with master, */master, refs/heads/master, refs/remotes/origin/master and so on)

Gitlab is configured to notify about pushes and merge requests. With push event (to master branch) this job works fine. New projects are not created on a merge request event though jenkins receives the request. 

[Trigger output (txt)](https://github.com/jenkinsci/gitlab-hook-plugin/files/202615/jenkins.txt)

Versions:

* GitLab Community Edition 8.5.1 8b7080d
* Jenkins ver. 1.642.3
* Gitlab Hook Plugin 1.4.1.1

**Comment by HadesArchitect** [comment]
I'm highly interested to fix the issue so I'll be glad to provide any additional information, play with versions and so on. Also, I have some experience with ruby if it can be useful for a research.

**Comment by javiplx** [comment]
I believe that your issue is already fixed by [current snapshot](https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/ruby-plugins/gitlab-hook/1.4.2-SNAPSHOT/). With recent gitlab releases, all the payloads have a object_kind (previously, only MR do), and the plugin get confused and believes everything is a standard push.
I'm still fixing a similar issue with tags, but I expect a full release soon. But for MR the snapshot should suffice, and it includes also support for commit statuses, in case you want to test (if you read the help, ignore the text about a patched gitlab, it does not apply anymore).

**Comment by HadesArchitect** [comment]
@javiplx Wow, such a good news! Well then, I will immediately test it and let you know about status update.

**Comment by HadesArchitect** [comment]
Should I use this file? https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/ruby-plugins/gitlab-hook/1.4.2-SNAPSHOT/gitlab-hook-1.4.2-20160327.215747-10.hpi

**Comment by HadesArchitect** [comment]
```
   ... THE SAME REQUEST ...
   "work_in_progress": false,
   "url": "http://git.tyre24.local/aleks/test-project/merge_requests/6",
   "action": "open"
 }
 Apr 04, 2016 2:59:29 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
 INFO: matching projects:
    - test-project
 Apr 04, 2016 2:59:29 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
 INFO: matching projects:
    - test-project
 Apr 04, 2016 2:59:29 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
 INFO: Created test-project-mr-456 for 456 from test-project
 test-project-mr-456 scheduled for build
 Apr 04, 2016 2:59:44 PM hudson.model.Run execute
 INFO: test-project-mr-456 #1 main build action completed: SUCCESS
```

It works now! Good job!

**Comment by HadesArchitect** [comment]
A. About commit statuses - sorry, but I can't confirm that it works: or it isn't work for me, or I don't know how to verify it =/ How can I check it? I've tried both ways, with 'commit statuses' or without them. No traces of any new data/comments in gitlab.

B. Second question is out of topic a little, but quite interesting for me: we are using 'Folders' plugin to keep our jobs properly organised, and my real jobs (not the test-project) are strored in the folders. But new merge-request jobs are created in the main space, which break the structure. Any way to make MR jobs respect parent folder? Can I somehow help?

C.  Jobs duplication. The plugin creates two jobs for me - one has a name of parent job WITH a folder name (like 'frontend/projectname-mr-123'), but with absolutely empty configuration (no git repo, nothing) and a second with a name WITHOUT folder name (like 'projectname-mr-123') but properly configured and functional. On a Merge Request accepting, the plugin deletes only second one job, and after that whole job with MRs are blocked - on any new request (creation/push into MR branch/close) the plugin fails with an exception:

```
   "action": "open"
 }
 Apr 04, 2016 3:39:36 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
 INFO: matching projects:
    - frontend/project-develop
 Apr 04, 2016 3:39:36 PM org.jruby.javasupport.JavaMethod invokeDirectWithExceptionHandling
 INFO: matching projects:
    - frontend/project-develop
Apr 04, 2016 3:39:36 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NameError - no constructorfor arguments (java.lang.IllegalArgumentException) on Java::OrgJrubyExceptions::RaiseException:
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:76:in `process_projects'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/models/api.rb:31:in `POST /build_now'
org/jruby/RubyMethod.java:118:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:1265:in `compile!'
org/jruby/RubyProc.java:249:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:851:in `route_eval'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:835:in `route!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:872:in `process_route'
org/jruby/RubyKernel.java:1174:in `catch'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:870:in `process_route'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:834:in `route!' org/jruby/RubyArray.java:1613:in `each'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:833:in `route!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:936:in `dispatch!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
org/jruby/RubyKernel.java:1174:in `catch'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:921:in `invoke'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:769:in `call!'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:755:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/showexceptions.rb:21:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/sinatra-1.3.3/lib/sinatra/base.rb:99:in `call'
/var/jenkins_home/plugins/gitlab-hook/WEB-INF/classes/models/root_action.rb:18:in `call'
file:/var/jenkins_home/plugins/ruby-runtime/WEB-INF/lib/jruby-rack-1.1.13.1.jar!/rack/handler/servlet.rb:22:in `call'
```

After manual deletion of the empty duplicated project, everything starts to work again.

D. "Display name". The new MR job will have a project name as a parent one but with '-mr-XYZ', but the same DISPLAY NAME as a parent, which looks strange.

All the points are out of the issue scope. Should I create new tickets?

**Comment by javiplx** [comment]
For the B & C might say yes to opening another issue (if possible in [Jenkins jira](https://issues.jenkins-ci.org/), with gitlab-hook plugin component). I believe they are probably very related issues.
Regarding D, leave on hold for a few days, because I believe it will be quite trivial (other automatically created projects do change the description, but I've never payed attention to MR ones).

**Comment by HadesArchitect** [comment]
Ok, thanks, I'll create an issue in jenkins jira.
