### ISSUE TITLE
Create Jenkins Job in a specific view

### ISSUE THREAD

**Issue by inforedaster** [jenkinsci/gitlab-hook-plugin#25]
hi

can we Create Jenkins Job in a specific view with gitlab-hook-plugin ?

thanks

**Comment by HadesArchitect** [comment]
+1

I have to mention, that as far as i know the issues have to be created in Jenkins jira (https://issues.jenkins-ci.org/secure/Dashboard.jspa) with a component gitlab-hook, not here.

**Comment by inforedaster** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-34087

**Comment by javiplx** [comment]
Thanks for reporting also in jira. Your question about "view" is related to folders plugin? If not, what "view" are you referring to?

**Comment by HadesArchitect** [comment]
There are two different things. Folders is a plugin, and views is a built-in jenkins feature.

**Comment by javiplx** [comment]
So, the "view" is the one I see rendered as tabs in main page? That was the only ones I was aware of.
If that is the case, then it depends on which projects are included on it. If for example, is a regular expression against project name, then they should appear in the right view (depending on the setting about using repo or project name when automatically creating new jobs).

**Comment by HadesArchitect** [comment]
Agree, with properly configured regexp it already works fine. (For me it works.)

**Comment by inforedaster** [comment]
list view in jenkins dashboard like picture :

[http://zeroturnaround.com/wp-content/uploads/2013/08/Jenkins-view.jpg](url)

**Comment by inforedaster** [comment]
@javiplx 
can you explain please !!

**Comment by HadesArchitect** [comment]
In a view settings:

![image](https://cloud.githubusercontent.com/assets/1742301/14356121/e01f77b6-fce3-11e5-9977-5ada7c6eda36.png)

**Comment by inforedaster** [comment]
@javiplx 
great thank you very much
