### ISSUE TITLE
webhook url for project in folder

### ISSUE THREAD

**Issue by d3xt3r01** [jenkinsci/gitlab-hook-plugin#33]
Hello,

For the past few days I've been rebasing my projects. One thing I did was move them from root jenkins and group them in folders.

I had http://site/jenkins/project/projectname as a webhook which stopped working. I've tried all the ways I can think of and found online with no luck. So I thought to try out this plugin.
```
http://site/jenkins/gitlab/build_now
#Yells: Hook executed successfully but returned HTTP 404 could not found template ''
http://site/jenkins/gitlab/build_now/projectname
#Yells some big html with error 500
```

**Comment by DThrasher** [comment]
I have the same issue. The http://site/jenkins/gitlab/build_now complains about a missing template.

The http://site/jenkins/gitlab/build_now/projectname web hook works for me, but has the side effect of triggering ALL projects accessing the same Gitlab repo, instead of just the project referenced in the URL.

I am using Jenkins ver. 2.7.1 and GitLab-Hook-Plugin 1.4.2

**Comment by d3xt3r01** [comment]
Updated jenkins to 2.23 / gitlab to 8.12.1 .. 
All works .. my hook now looks like this: https://site/jenkins/project/foldername/projectname/

**Comment by javiplx** [comment]
This is probably a mix of unclear documentation and real bugs.
On first place, if using plain _build_now_ endpoint it will execute all projects matching the repository & branch that came on the gitlab message. If no match is found, it tries to create a new project from template, and when no template is defined tries to search empty string, producing the 404 (this is a minor but real bug javiplx/jenkins-gitlab-hook-plugin#97)
When using _build_now/projectname_ endpoint, only that particular project is executed, and nothing should happen if it does not exists, but in neither of those cases other projects should be executed. I'm quite sure that I have a specific test for that, so it could be an issue related to jenkins2, which is yet untested. From the comments from @d3xt3r01, I understand that he is using the folders plugin, which has been reported not to work nicely with the _build_now_ plain endpoint. @DThrasher, are you also using it? In that case, maybe using the full name might work. If not, please report on javiplx/jenkins-gitlab-hook-plugin#98

**Comment by ZeusMinos** [comment]
@javiplx I am trying to kick a jenkins pipeline job using http://your-jenkins-server/gitlab/build_now/project_name from gitlab and I endup getting a "Hook executed successfully but returned HTTP 500 ". I tried kicking other jobs using  http://your-jenkins-server/gitlab/build_now/ and I can see the other jobs running, but the pipeline one it does not. 

this is what I have on the Jenkins pipeline job (just for testing)

payload, and gitlabBranch are project parameters

#!groovy

try {
    RetrivePayload()
} catch(e) {
    //NotifyFail()
    throw e
}

def RetrivePayload() {
    stage("gitlab hooks") {
        node {
            echo "$payload"
            echo "$gitlabBranch"
        }
    }
